// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Kg52a4mBin66DHY7vf0C4O1tzM0N0Ok',
    appId: '1:223036945856:web:8b8c4a460ea890d239c425',
    messagingSenderId: '223036945856',
    projectId: 'note-app-ac960',
    authDomain: 'note-app-ac960.firebaseapp.com',
    storageBucket: 'note-app-ac960.appspot.com',
    measurementId: 'G-EVH36Q4L82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKgvTgzwEhhViEQdTTvfgD-uBUF0DUiS4',
    appId: '1:223036945856:android:864eef5d36cc7e1c39c425',
    messagingSenderId: '223036945856',
    projectId: 'note-app-ac960',
    storageBucket: 'note-app-ac960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADzyNJMbannHeUhIYNL_JrgMXd2eyiQdI',
    appId: '1:223036945856:ios:032066d47e1f279239c425',
    messagingSenderId: '223036945856',
    projectId: 'note-app-ac960',
    storageBucket: 'note-app-ac960.appspot.com',
    iosBundleId: 'com.example.noteFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADzyNJMbannHeUhIYNL_JrgMXd2eyiQdI',
    appId: '1:223036945856:ios:18665ca4a788c04239c425',
    messagingSenderId: '223036945856',
    projectId: 'note-app-ac960',
    storageBucket: 'note-app-ac960.appspot.com',
    iosBundleId: 'com.example.noteFirebaseApp.RunnerTests',
  );
}
